# Generated by Django 3.1.2 on 2022-06-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0003_alter_bookedslot_id_alter_location_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedslot',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parkslot',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
